#!/usr/bin/env python3
"""
Data preparation script for SWE-bench.

This script:
1. Downloads SWE-bench dataset from HuggingFace
2. Converts it to slime's JSONL format
3. Splits into train/val/test sets
"""

import argparse
import json
import random
from pathlib import Path

try:
    from datasets import load_dataset
except ImportError:
    raise ImportError(
        "datasets library not found. Please install it with:\n"
        "  pip install datasets"
    )


def convert_swebench_to_slime_format(instance: dict, dataset_name: str = "") -> dict:
    """
    Convert a SWE-bench instance to slime's format.

    An example of a SWE-bench datum is as follows:
    
    instance_id: (str) - A formatted instance identifier, usually as repo_owner__repo_name-PR-number.
    patch: (str) - The gold patch, the patch generated by the PR (minus test-related code), that resolved the issue.
    repo: (str) - The repository owner/name identifier from GitHub.
    base_commit: (str) - The commit hash of the repository representing the HEAD of the repository before the solution PR is applied.
    hints_text: (str) - Comments made on the issue prior to the creation of the solution PR’s first commit creation date.
    created_at: (str) - The creation date of the pull request.
    test_patch: (str) - A test-file patch that was contributed by the solution PR.
    problem_statement: (str) - The issue title and body.
    version: (str) - Installation version to use for running evaluation.
    environment_setup_commit: (str) - commit hash to use for environment setup and installation.
    FAIL_TO_PASS: (str) - A json list of strings that represent the set of tests resolved by the PR and tied to the issue resolution.
    PASS_TO_PASS: (str) - A json list of strings that represent tests that should pass before and after the PR application.

    Args:
        instance: SWE-bench instance dict

    Returns:
        Dict in slime's JSONL format
    """
    # Extract fields
    instance_id = instance.get("instance_id", "unknown")
    problem_statement = instance.get("problem_statement", "")
    patch = instance.get("patch", "")  # Ground truth patch (for reference)
    test_patch = instance.get("test_patch", "")
    repo = instance.get("repo", "")
    base_commit = instance.get("base_commit", "")
    version = instance.get("version", "")
    hints_text = instance.get("hints_text", "")
    created_at = instance.get("created_at", "")
    environment_setup_commit = instance.get("environment_setup_commit", "")
    fail_to_pass = instance.get("FAIL_TO_PASS", "")
    pass_to_pass = instance.get("PASS_TO_PASS", "")

    #problem_statement += "<possible_solution>\n\n" + patch + "\n\n</possible_solution>\n" # !!!!!!!!!!!! only for debugging

    # Build slime sample
    slime_sample = {
        # Main fields
        "problem_statement": problem_statement,
        "patch": patch,  # Ground truth (optional, for reference)

        # Metadata for environment setup and reward computation
        "metadata": {
            "dataset": dataset_name,
            "instance_id": instance_id,
            "repo": repo,
            "base_commit": base_commit,
            "version": version,
            "test_patch": test_patch,
            "hints_text": hints_text,
            "created_at": created_at,
            "environment_setup_commit": environment_setup_commit,
            "FAIL_TO_PASS": fail_to_pass,
            "PASS_TO_PASS": pass_to_pass,
        }
    }

    return slime_sample


def convert_swerebench_to_slime_format(instance: dict, dataset_name: str = "") -> dict:
    # Extract fields
    instance_id = instance.get("instance_id", "unknown")
    problem_statement = instance.get("problem_statement", "")
    patch = instance.get("patch", "")  # Ground truth patch (for reference)
    test_patch = instance.get("test_patch", "")
    repo = instance.get("repo", "")
    base_commit = instance.get("base_commit", "")
    version = instance.get("version", "")
    hints_text = instance.get("hints_text", "")
    created_at = instance.get("created_at", "")
    environment_setup_commit = instance.get("environment_setup_commit", "")
    fail_to_pass = instance.get("FAIL_TO_PASS", "")
    pass_to_pass = instance.get("PASS_TO_PASS", "")


    slime_sample = {
        # Main fields
        "problem_statement": problem_statement,
        "patch": patch,  # Ground truth (optional, for reference)

        # Metadata for environment setup and reward computation
        "metadata": {
            "dataset": dataset_name,
            "instance_id": instance_id,
            "image_url": instance["image_name"],
            "install_config": instance["install_config"],
            "repo": repo,
            "base_commit": base_commit,
            "version": version,
            "test_patch": test_patch,
            "hints_text": hints_text,
            "created_at": created_at,
            "environment_setup_commit": environment_setup_commit,
            "FAIL_TO_PASS": fail_to_pass,
            "PASS_TO_PASS": pass_to_pass,
        }
    }

    if instance.get("workdir"):
        slime_sample["metadata"]["workdir"] = instance["workdir"]

    return slime_sample


def convert_scaleswe_to_slime_format(instance: dict, dataset_name: str = "") -> dict:
    """
    Convert a ScaleSWE instance to slime's format.

    Args:
        instance: ScaleSWE instance dict

    Returns:
        Dict in slime's JSONL format
    """
    # Extract fields
    instance_id = instance.get("instance_id", "unknown")
    problem_statement = instance.get("problem_statement", "")
    patch = instance.get("patch", "")  # Ground truth patch (for reference)
    test_patch = instance.get("f2p_patch", "")
    repo = instance.get("repo", "")
    base_commit = instance.get("parent_commit", "")
    version = instance.get("github_url", "")
    hints_text = instance.get("hints_text", "")
    created_at = instance.get("created_at", "")
    environment_setup_commit = instance.get("environment_setup_commit", "")
    fail_to_pass = instance.get("FAIL_TO_PASS", "")
    pass_to_pass = instance.get("PASS_TO_PASS", "")

    assert "image_url" in instance, f"Missing 'image_url' in instance {instance_id}"
    assert instance["image_url"] is not None, f"'image_url' is None in instance {instance_id}"

    # Build slime sample
    slime_sample = {
        # Main fields
        "problem_statement": problem_statement,
        "patch": patch,  # Ground truth (optional, for reference)

        # Metadata for environment setup and reward computation
        "metadata": {
            "dataset": dataset_name,
            "instance_id": instance_id,
            "image_url": instance["image_url"],
            "workdir": instance["workdir"],
            "pre_commands": instance["pre_commands"],
            "repo": repo,
            "base_commit": instance["parent_commit"],
            "version": version,
            "test_patch": instance["f2p_patch"],
            "hints_text": hints_text,
            "created_at": created_at,
            "environment_setup_commit": environment_setup_commit,
            "FAIL_TO_PASS": fail_to_pass,
            "PASS_TO_PASS": pass_to_pass,
        }
    }

    return slime_sample


def prepare_swebench_data(
    output_dir: Path,
    dataset_name: str = "princeton-nlp/SWE-bench_Verified",
    subset: str = None,
    train_size: int = 400,
    dev_size: int = 50,
    test_size: int = 50,
    seed: int = 42,
):
    """
    Download and prepare SWE-bench data.

    For datasets with a single split (e.g., SWE-bench_Verified with only "test"),
    the data is manually split into train/dev/test using the specified sizes.

    Args:
        output_dir: Directory to save JSONL files
        dataset_name: HuggingFace dataset name
        subset: Optional subset name (e.g., "test", "dev")
        train_size: Number of instances for training set
        dev_size: Number of instances for dev set
        test_size: Number of instances for test set
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading dataset: {dataset_name}")
    if subset:
        dataset = load_dataset(dataset_name, subset)
    else:
        dataset = load_dataset(dataset_name)

    # If the dataset has only one split, manually split into train/dev/test
    split_names = list(dataset.keys())
    if len(split_names) == 1:
        single_split = split_names[0]
        all_data = list(dataset[single_split])
        total = len(all_data)
        print(f"\nDataset has a single '{single_split}' split with {total} instances.")
        print(f"Shuffling with seed={seed} before splitting...")
        random.Random(seed).shuffle(all_data)
        print(f"Splitting into train({train_size})/dev({dev_size})/test({test_size})...")

        assert train_size + dev_size + test_size <= total, (
            f"Requested split sizes ({train_size}+{dev_size}+{test_size}={train_size+dev_size+test_size}) "
            f"exceed total instances ({total})"
        )

        splits = {
            "all": all_data,
            "train": all_data[:train_size],
            "dev": all_data[train_size:train_size + dev_size],
            "test": all_data[train_size + dev_size:train_size + dev_size + test_size],
        }
    else:
        # Use existing splits as-is
        splits = {name: list(dataset[name]) for name in split_names}

    # Process each split
    for split_name, split_data in splits.items():
        print(f"\nProcessing split: {split_name} ({len(split_data)} instances)")

        output_file = output_dir / f"swebench_{split_name}.jsonl"

        with open(output_file, "w") as f:
            for idx, instance in enumerate(split_data):
                # Convert to slime format
                slime_sample = convert_swebench_to_slime_format(instance, dataset_name=dataset_name)

                # Write JSONL
                f.write(json.dumps(slime_sample) + "\n")

                if (idx + 1) % 100 == 0:
                    print(f"  Processed {idx + 1} instances...")

        print(f"  Saved to: {output_file}")

    print("\nData preparation complete!")
    print(f"Files saved to: {output_dir}")

def prepare_swerebench_data(
    output_dir: Path,
    dataset_name: str = "nebius/SWE-rebench",
    subset: str = None,
    seed: int = 42,
):
    """
    Download and prepare SWE-rebench data.

    Args:
        output_dir: Directory to save JSONL files
        dataset_name: HuggingFace dataset name
        subset: Optional subset name (e.g., "test", "dev")
        seed: Random seed for shuffling (ensures reproducibility)
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading dataset: {dataset_name}")
    if subset:
        dataset = load_dataset(dataset_name, subset)
    else:
        dataset = load_dataset(dataset_name)
    
    split_names = list(dataset.keys())
    print(f"Dataset splits found: {split_names}")

    if "test" in split_names:
        single_split = "test"
    elif "train" in split_names:
        single_split = "train"
    
    all_data = []
    for instance in dataset[single_split]:
        if not item["image_name"]:
            continue
        if "language" in instance and instance["language"] != "python": # skip non-python instances in swe-rebench
            continue
        item = dict(instance)
        if dataset_name == "nebius/SWE-rebench-V2":
            item["workdir"] = '/' + item['repo'].split("/")[-1]
            if isinstance(item["install_config"]["install"], list):
                item["install_config"]["install"] = " && ".join(item["install_config"]["install"])
        all_data.append(item)
    total = len(all_data)
    print(f"\nDataset has a single '{single_split}' split with {total} instances.")
    print(f"Shuffling with seed={seed} before splitting...")
    random.Random(seed).shuffle(all_data)
    test_size = 200
    train_size = total - test_size
    print(f"Splitting into train({train_size})/test({test_size})...")

    splits = {
        "all": all_data,
        "train": all_data[:train_size],
        "test": all_data[train_size:train_size + test_size],
    }

    # Process each split
    for split_name, split_data in splits.items():
        print(f"\nProcessing split: {split_name} ({len(split_data)} instances)")

        output_file = output_dir / f"swerebench_{split_name}.jsonl"

        with open(output_file, "w") as f:
            for idx, instance in enumerate(split_data):
                # Convert to slime format
                slime_sample = convert_swerebench_to_slime_format(instance, dataset_name=dataset_name)

                # Write JSONL
                f.write(json.dumps(slime_sample) + "\n")

                if (idx + 1) % 1000 == 0:
                    print(f"  Processed {idx + 1} instances...")

        print(f"  Saved to: {output_file}")
    print("\nData preparation complete!")
    print(f"Files saved to: {output_dir}")

def prepare_scaleswe_data(
    output_dir: Path,
    dataset_name: str = "princeton-nlp/ScaleSWE",
    subset: str = None,
    seed: int = 42,
):
    """
    Download and prepare ScaleSWE data.

    Args:
        output_dir: Directory to save JSONL files
        dataset_name: HuggingFace dataset name
        subset: Optional subset name (e.g., "test", "dev")
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading dataset: {dataset_name}")
    if subset:
        dataset = load_dataset(dataset_name, subset)
    else:
        dataset = load_dataset(dataset_name)
    
    split_names = list(dataset.keys())
    print(f"Dataset splits found: {split_names}")
    
    if len(split_names) == 1:
        single_split = split_names[0]
        all_data = list(dataset[single_split])
        total = len(all_data)
        print(f"\nDataset has a single '{single_split}' split with {total} instances.")
        print(f"Shuffling with seed={seed} before splitting...")
        random.Random(seed).shuffle(all_data)
        test_size = 200
        train_size = total - test_size
        print(f"Splitting into train({train_size})/test({test_size})...")

        splits = {
            "all": all_data,
            "train": all_data[:train_size],
            "test": all_data[train_size:train_size + test_size],
        }
    else:
        # Use existing splits as-is
        splits = {name: list(dataset[name]) for name in split_names}

    # Process each split
    for split_name, split_data in splits.items():
        print(f"\nProcessing split: {split_name} ({len(split_data)} instances)")

        output_file = output_dir / f"scaleswe_{split_name}.jsonl"

        with open(output_file, "w") as f:
            for idx, instance in enumerate(split_data):
                # Convert to slime format
                slime_sample = convert_scaleswe_to_slime_format(instance, dataset_name=dataset_name)

                # Write JSONL
                f.write(json.dumps(slime_sample) + "\n")

                if (idx + 1) % 2000 == 0:
                    print(f"  Processed {idx + 1} instances...")

        print(f"  Saved to: {output_file}")

    print("\nData preparation complete!")
    print(f"Files saved to: {output_dir}")


def create_sample_subset(
    input_file: Path,
    output_file: Path,
    n_samples: int = 10
):
    """
    Create a small subset for testing.

    Args:
        input_file: Input JSONL file
        output_file: Output JSONL file
        n_samples: Number of samples to include
    """
    input_file = Path(input_file)
    output_file = Path(output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)

    print(f"Creating subset with {n_samples} samples")
    print(f"  Input: {input_file}")
    print(f"  Output: {output_file}")

    with open(input_file) as f_in, open(output_file, "w") as f_out:
        for idx, line in enumerate(f_in):
            if idx >= n_samples:
                break
            f_out.write(line)

    print(f"Subset created: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description="Prepare SWE-bench data for slime training"
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="data/swebench",
        help="Output directory for JSONL files",
    )
    parser.add_argument(
        "--dataset",
        type=str,
        default="princeton-nlp/SWE-bench_Verified",
        help="HuggingFace dataset name",
    )
    parser.add_argument(
        "--subset",
        type=str,
        default=None,
        help="Optional dataset subset",
    )
    parser.add_argument(
        "--train-size",
        type=int,
        default=400,
        help="Number of instances for training set (when manually splitting)",
    )
    parser.add_argument(
        "--dev-size",
        type=int,
        default=50,
        help="Number of instances for dev set (when manually splitting)",
    )
    parser.add_argument(
        "--test-size",
        type=int,
        default=50,
        help="Number of instances for test set (when manually splitting)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for shuffling before splitting (ensures reproducibility)",
    )

    args = parser.parse_args()

    if "SWE-bench_Verified" in args.dataset:
        # Prepare main dataset
        prepare_swebench_data(
            output_dir=args.output_dir,
            dataset_name=args.dataset,
            subset=args.subset,
            train_size=args.train_size,
            dev_size=args.dev_size,
            test_size=args.test_size,
            seed=args.seed,
        )
        # Always create small (10%) versions of each split
        print("\n" + "=" * 60)
        print("Creating small (10%) subsets...")
        print("=" * 60)

        output_dir = Path(args.output_dir)

        for split_name, full_size in [("train", args.train_size), ("dev", args.dev_size), ("test", args.test_size)]:
            split_file = output_dir / f"swebench_{split_name}.jsonl"
            if split_file.exists():
                small_size = max(1, full_size // 10)
                create_sample_subset(
                    input_file=split_file,
                    output_file=output_dir / f"swebench_{split_name}_small.jsonl",
                    n_samples=small_size,
                )
    elif "SWE-rebench" in args.dataset:
        prepare_swerebench_data(
            output_dir=args.output_dir,
            dataset_name=args.dataset,
            subset=args.subset,
            seed=args.seed,
        )
    elif "Scale-SWE" in args.dataset:
        prepare_scaleswe_data(
            output_dir=args.output_dir,
            dataset_name=args.dataset,
            subset=args.subset,
            seed=args.seed,
        )
    else:
        raise ValueError(f"Unsupported dataset: {args.dataset}")


if __name__ == "__main__":
    main()
